// File: Multiplier_KoggeStone.v
// Generated by MyHDL 0.11
// Date: Sun Sep  5 02:16:58 2021


`timescale 1ns/10ps

module Multiplier_KoggeStone (
    A,
    B,
    clock,
    OUTS
);

input clock;
input [7:0] A;
input [7:0] B;
output [15:0] OUTS;
wire [15:0] OUTS;

wire [28:0] OutBits_ct;
wire [63:0] Multiplier0_OutBits_ppg;
wire [63:0] Multiplier0_PPG0_outs_vec;
wire [0:0] Multiplier0_PPG0_AND0_out;
wire [0:0] Multiplier0_PPG0_AND1_out;
wire [0:0] Multiplier0_PPG0_AND2_out;
wire [0:0] Multiplier0_PPG0_AND3_out;
wire [0:0] Multiplier0_PPG0_AND4_out;
wire [0:0] Multiplier0_PPG0_AND5_out;
wire [0:0] Multiplier0_PPG0_AND6_out;
wire [0:0] Multiplier0_PPG0_AND7_out;
wire [0:0] Multiplier0_PPG0_AND8_out;
wire [0:0] Multiplier0_PPG0_AND9_out;
wire [0:0] Multiplier0_PPG0_AND10_out;
wire [0:0] Multiplier0_PPG0_AND11_out;
wire [0:0] Multiplier0_PPG0_AND12_out;
wire [0:0] Multiplier0_PPG0_AND13_out;
wire [0:0] Multiplier0_PPG0_AND14_out;
wire [0:0] Multiplier0_PPG0_AND15_out;
wire [0:0] Multiplier0_PPG0_AND16_out;
wire [0:0] Multiplier0_PPG0_AND17_out;
wire [0:0] Multiplier0_PPG0_AND18_out;
wire [0:0] Multiplier0_PPG0_AND19_out;
wire [0:0] Multiplier0_PPG0_AND20_out;
wire [0:0] Multiplier0_PPG0_AND21_out;
wire [0:0] Multiplier0_PPG0_AND22_out;
wire [0:0] Multiplier0_PPG0_AND23_out;
wire [0:0] Multiplier0_PPG0_AND24_out;
wire [0:0] Multiplier0_PPG0_AND25_out;
wire [0:0] Multiplier0_PPG0_AND26_out;
wire [0:0] Multiplier0_PPG0_AND27_out;
wire [0:0] Multiplier0_PPG0_AND28_out;
wire [0:0] Multiplier0_PPG0_AND29_out;
wire [0:0] Multiplier0_PPG0_AND30_out;
wire [0:0] Multiplier0_PPG0_AND31_out;
wire [0:0] Multiplier0_PPG0_AND32_out;
wire [0:0] Multiplier0_PPG0_AND33_out;
wire [0:0] Multiplier0_PPG0_AND34_out;
wire [0:0] Multiplier0_PPG0_AND35_out;
wire [0:0] Multiplier0_PPG0_AND36_out;
wire [0:0] Multiplier0_PPG0_AND37_out;
wire [0:0] Multiplier0_PPG0_AND38_out;
wire [0:0] Multiplier0_PPG0_AND39_out;
wire [0:0] Multiplier0_PPG0_AND40_out;
wire [0:0] Multiplier0_PPG0_AND41_out;
wire [0:0] Multiplier0_PPG0_AND42_out;
wire [0:0] Multiplier0_PPG0_AND43_out;
wire [0:0] Multiplier0_PPG0_AND44_out;
wire [0:0] Multiplier0_PPG0_AND45_out;
wire [0:0] Multiplier0_PPG0_AND46_out;
wire [0:0] Multiplier0_PPG0_AND47_out;
wire [0:0] Multiplier0_PPG0_AND48_out;
wire [0:0] Multiplier0_PPG0_AND49_out;
wire [0:0] Multiplier0_PPG0_AND50_out;
wire [0:0] Multiplier0_PPG0_AND51_out;
wire [0:0] Multiplier0_PPG0_AND52_out;
wire [0:0] Multiplier0_PPG0_AND53_out;
wire [0:0] Multiplier0_PPG0_AND54_out;
wire [0:0] Multiplier0_PPG0_AND55_out;
wire [0:0] Multiplier0_PPG0_AND56_out;
wire [0:0] Multiplier0_PPG0_AND57_out;
wire [0:0] Multiplier0_PPG0_AND58_out;
wire [0:0] Multiplier0_PPG0_AND59_out;
wire [0:0] Multiplier0_PPG0_AND60_out;
wire [0:0] Multiplier0_PPG0_AND61_out;
wire [0:0] Multiplier0_PPG0_AND62_out;
wire [0:0] Multiplier0_PPG0_AND63_out;
wire [28:0] Multiplier0_CompressorTree0_outs_vec;
wire [0:0] Multiplier0_CompressorTree0_AC320_out1;
wire [0:0] Multiplier0_CompressorTree0_AC320_out2;
wire [0:0] Multiplier0_CompressorTree0_AC420_out1;
wire [0:0] Multiplier0_CompressorTree0_AC420_out2;
wire [0:0] Multiplier0_CompressorTree0_AC421_out1;
wire [0:0] Multiplier0_CompressorTree0_AC421_out2;
wire [0:0] Multiplier0_CompressorTree0_AC422_out1;
wire [0:0] Multiplier0_CompressorTree0_AC422_out2;
wire [0:0] Multiplier0_CompressorTree0_AC321_out1;
wire [0:0] Multiplier0_CompressorTree0_AC321_out2;
wire [0:0] Multiplier0_CompressorTree0_AC322_out1;
wire [0:0] Multiplier0_CompressorTree0_AC322_out2;
wire [0:0] Multiplier0_CompressorTree0_AC423_out1;
wire [0:0] Multiplier0_CompressorTree0_AC423_out2;
wire [0:0] Multiplier0_CompressorTree0_AC323_out1;
wire [0:0] Multiplier0_CompressorTree0_AC323_out2;
wire [0:0] Multiplier0_CompressorTree0_AC324_out1;
wire [0:0] Multiplier0_CompressorTree0_AC324_out2;
wire [0:0] Multiplier0_CompressorTree0_AC325_out1;
wire [0:0] Multiplier0_CompressorTree0_AC325_out2;
wire [0:0] Multiplier0_CompressorTree0_FA0_cout;
wire [0:0] Multiplier0_CompressorTree0_FA0_sum;
wire [0:0] Multiplier0_CompressorTree0_AC424_out1;
wire [0:0] Multiplier0_CompressorTree0_AC424_out2;
wire [0:0] Multiplier0_CompressorTree0_AC326_out1;
wire [0:0] Multiplier0_CompressorTree0_AC326_out2;
wire [0:0] Multiplier0_CompressorTree0_AC327_out1;
wire [0:0] Multiplier0_CompressorTree0_AC327_out2;
wire [0:0] Multiplier0_CompressorTree0_AC328_out1;
wire [0:0] Multiplier0_CompressorTree0_AC328_out2;
wire [0:0] Multiplier0_CompressorTree0_FA1_cout;
wire [0:0] Multiplier0_CompressorTree0_FA1_sum;
wire [0:0] Multiplier0_CompressorTree0_FA2_cout;
wire [0:0] Multiplier0_CompressorTree0_FA2_sum;
wire [0:0] Multiplier0_CompressorTree0_HA0_cout;
wire [0:0] Multiplier0_CompressorTree0_HA0_sum;
wire [0:0] Multiplier0_CompressorTree0_AC425_out1;
wire [0:0] Multiplier0_CompressorTree0_AC425_out2;
wire [0:0] Multiplier0_CompressorTree0_AC329_out1;
wire [0:0] Multiplier0_CompressorTree0_AC329_out2;
wire [0:0] Multiplier0_CompressorTree0_AC426_out1;
wire [0:0] Multiplier0_CompressorTree0_AC426_out2;
wire [0:0] Multiplier0_CompressorTree0_AC3210_out1;
wire [0:0] Multiplier0_CompressorTree0_AC3210_out2;
wire [0:0] Multiplier0_CompressorTree0_AC427_out1;
wire [0:0] Multiplier0_CompressorTree0_AC427_out2;
wire [0:0] Multiplier0_CompressorTree0_AC3211_out1;
wire [0:0] Multiplier0_CompressorTree0_AC3211_out2;
wire [0:0] Multiplier0_CompressorTree0_FA3_cout;
wire [0:0] Multiplier0_CompressorTree0_FA3_sum;
wire [0:0] Multiplier0_CompressorTree0_FA4_cout;
wire [0:0] Multiplier0_CompressorTree0_FA4_sum;
wire [0:0] Multiplier0_CompressorTree0_FA5_cout;
wire [0:0] Multiplier0_CompressorTree0_FA5_sum;
wire [0:0] Multiplier0_CompressorTree0_FA6_cout;
wire [0:0] Multiplier0_CompressorTree0_FA6_sum;
wire [15:0] KoggeStone0_outs_vec;
wire [0:0] KoggeStone0_PG_Generator00_g;
wire [0:0] KoggeStone0_PG_Generator00_p;
wire [0:0] KoggeStone0_PG_Generator10_g;
wire [0:0] KoggeStone0_PG_Generator10_p;
wire [0:0] KoggeStone0_PG_Generator11_g;
wire [0:0] KoggeStone0_PG_Generator11_p;
wire [0:0] KoggeStone0_PG_Generator12_g;
wire [0:0] KoggeStone0_PG_Generator12_p;
wire [0:0] KoggeStone0_PG_Generator13_g;
wire [0:0] KoggeStone0_PG_Generator13_p;
wire [0:0] KoggeStone0_PG_Generator14_g;
wire [0:0] KoggeStone0_PG_Generator14_p;
wire [0:0] KoggeStone0_PG_Generator15_g;
wire [0:0] KoggeStone0_PG_Generator15_p;
wire [0:0] KoggeStone0_PG_Generator16_g;
wire [0:0] KoggeStone0_PG_Generator16_p;
wire [0:0] KoggeStone0_PG_Generator17_g;
wire [0:0] KoggeStone0_PG_Generator17_p;
wire [0:0] KoggeStone0_PG_Generator18_g;
wire [0:0] KoggeStone0_PG_Generator18_p;
wire [0:0] KoggeStone0_PG_Generator19_g;
wire [0:0] KoggeStone0_PG_Generator19_p;
wire [0:0] KoggeStone0_PG_Generator110_g;
wire [0:0] KoggeStone0_PG_Generator110_p;
wire [0:0] KoggeStone0_PG_Generator111_g;
wire [0:0] KoggeStone0_PG_Generator111_p;
wire [0:0] KoggeStone0_PG_Generator112_g;
wire [0:0] KoggeStone0_PG_Generator112_p;
wire [0:0] KoggeStone0_PG_Generator113_g;
wire [0:0] KoggeStone0_PG_Generator113_p;
wire [0:0] KoggeStone0_GrayCircle0_go;
wire [0:0] KoggeStone0_BlackCircle0_go;
wire [0:0] KoggeStone0_BlackCircle0_po;
wire [0:0] KoggeStone0_BlackCircle1_go;
wire [0:0] KoggeStone0_BlackCircle1_po;
wire [0:0] KoggeStone0_BlackCircle2_go;
wire [0:0] KoggeStone0_BlackCircle2_po;
wire [0:0] KoggeStone0_BlackCircle3_go;
wire [0:0] KoggeStone0_BlackCircle3_po;
wire [0:0] KoggeStone0_BlackCircle4_go;
wire [0:0] KoggeStone0_BlackCircle4_po;
wire [0:0] KoggeStone0_BlackCircle5_go;
wire [0:0] KoggeStone0_BlackCircle5_po;
wire [0:0] KoggeStone0_BlackCircle6_go;
wire [0:0] KoggeStone0_BlackCircle6_po;
wire [0:0] KoggeStone0_BlackCircle7_go;
wire [0:0] KoggeStone0_BlackCircle7_po;
wire [0:0] KoggeStone0_BlackCircle8_go;
wire [0:0] KoggeStone0_BlackCircle8_po;
wire [0:0] KoggeStone0_BlackCircle9_go;
wire [0:0] KoggeStone0_BlackCircle9_po;
wire [0:0] KoggeStone0_BlackCircle10_go;
wire [0:0] KoggeStone0_BlackCircle10_po;
wire [0:0] KoggeStone0_BlackCircle11_go;
wire [0:0] KoggeStone0_BlackCircle11_po;
wire [0:0] KoggeStone0_BlackCircle12_go;
wire [0:0] KoggeStone0_BlackCircle12_po;
wire [0:0] KoggeStone0_GrayCircle1_go;
wire [0:0] KoggeStone0_GrayCircle2_go;
wire [0:0] KoggeStone0_BlackCircle13_go;
wire [0:0] KoggeStone0_BlackCircle13_po;
wire [0:0] KoggeStone0_BlackCircle14_go;
wire [0:0] KoggeStone0_BlackCircle14_po;
wire [0:0] KoggeStone0_BlackCircle15_go;
wire [0:0] KoggeStone0_BlackCircle15_po;
wire [0:0] KoggeStone0_BlackCircle16_go;
wire [0:0] KoggeStone0_BlackCircle16_po;
wire [0:0] KoggeStone0_BlackCircle17_go;
wire [0:0] KoggeStone0_BlackCircle17_po;
wire [0:0] KoggeStone0_BlackCircle18_go;
wire [0:0] KoggeStone0_BlackCircle18_po;
wire [0:0] KoggeStone0_BlackCircle19_go;
wire [0:0] KoggeStone0_BlackCircle19_po;
wire [0:0] KoggeStone0_BlackCircle20_go;
wire [0:0] KoggeStone0_BlackCircle20_po;
wire [0:0] KoggeStone0_BlackCircle21_go;
wire [0:0] KoggeStone0_BlackCircle21_po;
wire [0:0] KoggeStone0_BlackCircle22_go;
wire [0:0] KoggeStone0_BlackCircle22_po;
wire [0:0] KoggeStone0_BlackCircle23_go;
wire [0:0] KoggeStone0_BlackCircle23_po;
wire [0:0] KoggeStone0_GrayCircle3_go;
wire [0:0] KoggeStone0_GrayCircle4_go;
wire [0:0] KoggeStone0_GrayCircle5_go;
wire [0:0] KoggeStone0_GrayCircle6_go;
wire [0:0] KoggeStone0_BlackCircle24_go;
wire [0:0] KoggeStone0_BlackCircle24_po;
wire [0:0] KoggeStone0_BlackCircle25_go;
wire [0:0] KoggeStone0_BlackCircle25_po;
wire [0:0] KoggeStone0_BlackCircle26_go;
wire [0:0] KoggeStone0_BlackCircle26_po;
wire [0:0] KoggeStone0_BlackCircle27_go;
wire [0:0] KoggeStone0_BlackCircle27_po;
wire [0:0] KoggeStone0_BlackCircle28_go;
wire [0:0] KoggeStone0_BlackCircle28_po;
wire [0:0] KoggeStone0_BlackCircle29_go;
wire [0:0] KoggeStone0_BlackCircle29_po;
wire [0:0] KoggeStone0_BlackCircle30_go;
wire [0:0] KoggeStone0_BlackCircle30_po;
wire [0:0] KoggeStone0_GrayCircle7_go;
wire [0:0] KoggeStone0_GrayCircle8_go;
wire [0:0] KoggeStone0_GrayCircle9_go;
wire [0:0] KoggeStone0_GrayCircle10_go;
wire [0:0] KoggeStone0_GrayCircle11_go;
wire [0:0] KoggeStone0_GrayCircle12_go;
wire [0:0] KoggeStone0_GrayCircle13_go;
wire [0:0] KoggeStone0_FinalSum0_sum;
wire [0:0] KoggeStone0_FinalSum1_sum;
wire [0:0] KoggeStone0_FinalSum2_sum;
wire [0:0] KoggeStone0_FinalSum3_sum;
wire [0:0] KoggeStone0_FinalSum4_sum;
wire [0:0] KoggeStone0_FinalSum5_sum;
wire [0:0] KoggeStone0_FinalSum6_sum;
wire [0:0] KoggeStone0_FinalSum7_sum;
wire [0:0] KoggeStone0_FinalSum8_sum;
wire [0:0] KoggeStone0_FinalSum9_sum;
wire [0:0] KoggeStone0_FinalSum10_sum;
wire [0:0] KoggeStone0_FinalSum11_sum;
wire [0:0] KoggeStone0_FinalSum12_sum;
wire [0:0] KoggeStone0_FinalSum13_sum;

assign Multiplier0_PPG0_outs_vec[63] = Multiplier0_PPG0_AND63_out[0];
assign Multiplier0_PPG0_outs_vec[62] = Multiplier0_PPG0_AND61_out[0];
assign Multiplier0_PPG0_outs_vec[61] = Multiplier0_PPG0_AND62_out[0];
assign Multiplier0_PPG0_outs_vec[60] = Multiplier0_PPG0_AND58_out[0];
assign Multiplier0_PPG0_outs_vec[59] = Multiplier0_PPG0_AND59_out[0];
assign Multiplier0_PPG0_outs_vec[58] = Multiplier0_PPG0_AND60_out[0];
assign Multiplier0_PPG0_outs_vec[57] = Multiplier0_PPG0_AND54_out[0];
assign Multiplier0_PPG0_outs_vec[56] = Multiplier0_PPG0_AND55_out[0];
assign Multiplier0_PPG0_outs_vec[55] = Multiplier0_PPG0_AND56_out[0];
assign Multiplier0_PPG0_outs_vec[54] = Multiplier0_PPG0_AND57_out[0];
assign Multiplier0_PPG0_outs_vec[53] = Multiplier0_PPG0_AND49_out[0];
assign Multiplier0_PPG0_outs_vec[52] = Multiplier0_PPG0_AND50_out[0];
assign Multiplier0_PPG0_outs_vec[51] = Multiplier0_PPG0_AND51_out[0];
assign Multiplier0_PPG0_outs_vec[50] = Multiplier0_PPG0_AND52_out[0];
assign Multiplier0_PPG0_outs_vec[49] = Multiplier0_PPG0_AND53_out[0];
assign Multiplier0_PPG0_outs_vec[48] = Multiplier0_PPG0_AND43_out[0];
assign Multiplier0_PPG0_outs_vec[47] = Multiplier0_PPG0_AND44_out[0];
assign Multiplier0_PPG0_outs_vec[46] = Multiplier0_PPG0_AND45_out[0];
assign Multiplier0_PPG0_outs_vec[45] = Multiplier0_PPG0_AND46_out[0];
assign Multiplier0_PPG0_outs_vec[44] = Multiplier0_PPG0_AND47_out[0];
assign Multiplier0_PPG0_outs_vec[43] = Multiplier0_PPG0_AND48_out[0];
assign Multiplier0_PPG0_outs_vec[42] = Multiplier0_PPG0_AND36_out[0];
assign Multiplier0_PPG0_outs_vec[41] = Multiplier0_PPG0_AND37_out[0];
assign Multiplier0_PPG0_outs_vec[40] = Multiplier0_PPG0_AND38_out[0];
assign Multiplier0_PPG0_outs_vec[39] = Multiplier0_PPG0_AND39_out[0];
assign Multiplier0_PPG0_outs_vec[38] = Multiplier0_PPG0_AND40_out[0];
assign Multiplier0_PPG0_outs_vec[37] = Multiplier0_PPG0_AND41_out[0];
assign Multiplier0_PPG0_outs_vec[36] = Multiplier0_PPG0_AND42_out[0];
assign Multiplier0_PPG0_outs_vec[35] = Multiplier0_PPG0_AND28_out[0];
assign Multiplier0_PPG0_outs_vec[34] = Multiplier0_PPG0_AND29_out[0];
assign Multiplier0_PPG0_outs_vec[33] = Multiplier0_PPG0_AND30_out[0];
assign Multiplier0_PPG0_outs_vec[32] = Multiplier0_PPG0_AND31_out[0];
assign Multiplier0_PPG0_outs_vec[31] = Multiplier0_PPG0_AND32_out[0];
assign Multiplier0_PPG0_outs_vec[30] = Multiplier0_PPG0_AND33_out[0];
assign Multiplier0_PPG0_outs_vec[29] = Multiplier0_PPG0_AND34_out[0];
assign Multiplier0_PPG0_outs_vec[28] = Multiplier0_PPG0_AND35_out[0];
assign Multiplier0_PPG0_outs_vec[27] = Multiplier0_PPG0_AND21_out[0];
assign Multiplier0_PPG0_outs_vec[26] = Multiplier0_PPG0_AND22_out[0];
assign Multiplier0_PPG0_outs_vec[25] = Multiplier0_PPG0_AND23_out[0];
assign Multiplier0_PPG0_outs_vec[24] = Multiplier0_PPG0_AND24_out[0];
assign Multiplier0_PPG0_outs_vec[23] = Multiplier0_PPG0_AND25_out[0];
assign Multiplier0_PPG0_outs_vec[22] = Multiplier0_PPG0_AND26_out[0];
assign Multiplier0_PPG0_outs_vec[21] = Multiplier0_PPG0_AND27_out[0];
assign Multiplier0_PPG0_outs_vec[20] = Multiplier0_PPG0_AND15_out[0];
assign Multiplier0_PPG0_outs_vec[19] = Multiplier0_PPG0_AND16_out[0];
assign Multiplier0_PPG0_outs_vec[18] = Multiplier0_PPG0_AND17_out[0];
assign Multiplier0_PPG0_outs_vec[17] = Multiplier0_PPG0_AND18_out[0];
assign Multiplier0_PPG0_outs_vec[16] = Multiplier0_PPG0_AND19_out[0];
assign Multiplier0_PPG0_outs_vec[15] = Multiplier0_PPG0_AND20_out[0];
assign Multiplier0_PPG0_outs_vec[14] = Multiplier0_PPG0_AND10_out[0];
assign Multiplier0_PPG0_outs_vec[13] = Multiplier0_PPG0_AND11_out[0];
assign Multiplier0_PPG0_outs_vec[12] = Multiplier0_PPG0_AND12_out[0];
assign Multiplier0_PPG0_outs_vec[11] = Multiplier0_PPG0_AND13_out[0];
assign Multiplier0_PPG0_outs_vec[10] = Multiplier0_PPG0_AND14_out[0];
assign Multiplier0_PPG0_outs_vec[9] = Multiplier0_PPG0_AND6_out[0];
assign Multiplier0_PPG0_outs_vec[8] = Multiplier0_PPG0_AND7_out[0];
assign Multiplier0_PPG0_outs_vec[7] = Multiplier0_PPG0_AND8_out[0];
assign Multiplier0_PPG0_outs_vec[6] = Multiplier0_PPG0_AND9_out[0];
assign Multiplier0_PPG0_outs_vec[5] = Multiplier0_PPG0_AND3_out[0];
assign Multiplier0_PPG0_outs_vec[4] = Multiplier0_PPG0_AND4_out[0];
assign Multiplier0_PPG0_outs_vec[3] = Multiplier0_PPG0_AND5_out[0];
assign Multiplier0_PPG0_outs_vec[2] = Multiplier0_PPG0_AND1_out[0];
assign Multiplier0_PPG0_outs_vec[1] = Multiplier0_PPG0_AND2_out[0];
assign Multiplier0_PPG0_outs_vec[0] = Multiplier0_PPG0_AND0_out[0];
assign Multiplier0_CompressorTree0_outs_vec[28] = Multiplier0_CompressorTree0_FA6_cout[0];
assign Multiplier0_CompressorTree0_outs_vec[27] = Multiplier0_OutBits_ppg[63];
assign Multiplier0_CompressorTree0_outs_vec[26] = Multiplier0_CompressorTree0_FA5_cout[0];
assign Multiplier0_CompressorTree0_outs_vec[25] = Multiplier0_CompressorTree0_FA6_sum[0];
assign Multiplier0_CompressorTree0_outs_vec[24] = Multiplier0_CompressorTree0_FA4_cout[0];
assign Multiplier0_CompressorTree0_outs_vec[23] = Multiplier0_CompressorTree0_FA5_sum[0];
assign Multiplier0_CompressorTree0_outs_vec[22] = Multiplier0_CompressorTree0_FA4_sum[0];
assign Multiplier0_CompressorTree0_outs_vec[21] = Multiplier0_CompressorTree0_FA1_cout[0];
assign Multiplier0_CompressorTree0_outs_vec[20] = Multiplier0_CompressorTree0_FA3_cout[0];
assign Multiplier0_CompressorTree0_outs_vec[19] = Multiplier0_CompressorTree0_FA1_sum[0];
assign Multiplier0_CompressorTree0_outs_vec[18] = Multiplier0_CompressorTree0_FA3_sum[0];
assign Multiplier0_CompressorTree0_outs_vec[17] = Multiplier0_CompressorTree0_AC325_out2[0];
assign Multiplier0_CompressorTree0_outs_vec[16] = Multiplier0_CompressorTree0_AC3211_out2[0];
assign Multiplier0_CompressorTree0_outs_vec[15] = Multiplier0_CompressorTree0_AC3211_out1[0];
assign Multiplier0_CompressorTree0_outs_vec[14] = Multiplier0_CompressorTree0_AC427_out2[0];
assign Multiplier0_CompressorTree0_outs_vec[13] = Multiplier0_CompressorTree0_AC427_out1[0];
assign Multiplier0_CompressorTree0_outs_vec[12] = Multiplier0_CompressorTree0_AC3210_out2[0];
assign Multiplier0_CompressorTree0_outs_vec[11] = Multiplier0_CompressorTree0_AC3210_out1[0];
assign Multiplier0_CompressorTree0_outs_vec[10] = Multiplier0_CompressorTree0_AC426_out2[0];
assign Multiplier0_CompressorTree0_outs_vec[9] = Multiplier0_CompressorTree0_AC426_out1[0];
assign Multiplier0_CompressorTree0_outs_vec[8] = Multiplier0_CompressorTree0_AC329_out2[0];
assign Multiplier0_CompressorTree0_outs_vec[7] = Multiplier0_CompressorTree0_AC329_out1[0];
assign Multiplier0_CompressorTree0_outs_vec[6] = Multiplier0_CompressorTree0_AC425_out2[0];
assign Multiplier0_CompressorTree0_outs_vec[5] = Multiplier0_CompressorTree0_AC425_out1[0];
assign Multiplier0_CompressorTree0_outs_vec[4] = Multiplier0_CompressorTree0_AC320_out2[0];
assign Multiplier0_CompressorTree0_outs_vec[3] = Multiplier0_CompressorTree0_AC320_out1[0];
assign Multiplier0_CompressorTree0_outs_vec[2] = Multiplier0_OutBits_ppg[2];
assign Multiplier0_CompressorTree0_outs_vec[1] = Multiplier0_OutBits_ppg[1];
assign Multiplier0_CompressorTree0_outs_vec[0] = Multiplier0_OutBits_ppg[0];
assign KoggeStone0_outs_vec[15] = KoggeStone0_GrayCircle13_go[0];
assign KoggeStone0_outs_vec[14] = KoggeStone0_FinalSum13_sum[0];
assign KoggeStone0_outs_vec[13] = KoggeStone0_FinalSum12_sum[0];
assign KoggeStone0_outs_vec[12] = KoggeStone0_FinalSum11_sum[0];
assign KoggeStone0_outs_vec[11] = KoggeStone0_FinalSum10_sum[0];
assign KoggeStone0_outs_vec[10] = KoggeStone0_FinalSum9_sum[0];
assign KoggeStone0_outs_vec[9] = KoggeStone0_FinalSum8_sum[0];
assign KoggeStone0_outs_vec[8] = KoggeStone0_FinalSum7_sum[0];
assign KoggeStone0_outs_vec[7] = KoggeStone0_FinalSum6_sum[0];
assign KoggeStone0_outs_vec[6] = KoggeStone0_FinalSum5_sum[0];
assign KoggeStone0_outs_vec[5] = KoggeStone0_FinalSum4_sum[0];
assign KoggeStone0_outs_vec[4] = KoggeStone0_FinalSum3_sum[0];
assign KoggeStone0_outs_vec[3] = KoggeStone0_FinalSum2_sum[0];
assign KoggeStone0_outs_vec[2] = KoggeStone0_FinalSum1_sum[0];
assign KoggeStone0_outs_vec[1] = KoggeStone0_FinalSum0_sum[0];
assign KoggeStone0_outs_vec[0] = KoggeStone0_PG_Generator00_p[0];



assign Multiplier0_PPG0_AND0_out = (A[0] & B[0]);



assign Multiplier0_PPG0_AND1_out = (A[1] & B[0]);



assign Multiplier0_PPG0_AND2_out = (A[0] & B[1]);



assign Multiplier0_PPG0_AND3_out = (A[2] & B[0]);



assign Multiplier0_PPG0_AND4_out = (A[1] & B[1]);



assign Multiplier0_PPG0_AND5_out = (A[0] & B[2]);



assign Multiplier0_PPG0_AND6_out = (A[3] & B[0]);



assign Multiplier0_PPG0_AND7_out = (A[2] & B[1]);



assign Multiplier0_PPG0_AND8_out = (A[1] & B[2]);



assign Multiplier0_PPG0_AND9_out = (A[0] & B[3]);



assign Multiplier0_PPG0_AND10_out = (A[4] & B[0]);



assign Multiplier0_PPG0_AND11_out = (A[3] & B[1]);



assign Multiplier0_PPG0_AND12_out = (A[2] & B[2]);



assign Multiplier0_PPG0_AND13_out = (A[1] & B[3]);



assign Multiplier0_PPG0_AND14_out = (A[0] & B[4]);



assign Multiplier0_PPG0_AND15_out = (A[5] & B[0]);



assign Multiplier0_PPG0_AND16_out = (A[4] & B[1]);



assign Multiplier0_PPG0_AND17_out = (A[3] & B[2]);



assign Multiplier0_PPG0_AND18_out = (A[2] & B[3]);



assign Multiplier0_PPG0_AND19_out = (A[1] & B[4]);



assign Multiplier0_PPG0_AND20_out = (A[0] & B[5]);



assign Multiplier0_PPG0_AND21_out = (A[6] & B[0]);



assign Multiplier0_PPG0_AND22_out = (A[5] & B[1]);



assign Multiplier0_PPG0_AND23_out = (A[4] & B[2]);



assign Multiplier0_PPG0_AND24_out = (A[3] & B[3]);



assign Multiplier0_PPG0_AND25_out = (A[2] & B[4]);



assign Multiplier0_PPG0_AND26_out = (A[1] & B[5]);



assign Multiplier0_PPG0_AND27_out = (A[0] & B[6]);



assign Multiplier0_PPG0_AND28_out = (A[7] & B[0]);



assign Multiplier0_PPG0_AND29_out = (A[6] & B[1]);



assign Multiplier0_PPG0_AND30_out = (A[5] & B[2]);



assign Multiplier0_PPG0_AND31_out = (A[4] & B[3]);



assign Multiplier0_PPG0_AND32_out = (A[3] & B[4]);



assign Multiplier0_PPG0_AND33_out = (A[2] & B[5]);



assign Multiplier0_PPG0_AND34_out = (A[1] & B[6]);



assign Multiplier0_PPG0_AND35_out = (A[0] & B[7]);



assign Multiplier0_PPG0_AND36_out = (A[7] & B[1]);



assign Multiplier0_PPG0_AND37_out = (A[6] & B[2]);



assign Multiplier0_PPG0_AND38_out = (A[5] & B[3]);



assign Multiplier0_PPG0_AND39_out = (A[4] & B[4]);



assign Multiplier0_PPG0_AND40_out = (A[3] & B[5]);



assign Multiplier0_PPG0_AND41_out = (A[2] & B[6]);



assign Multiplier0_PPG0_AND42_out = (A[1] & B[7]);



assign Multiplier0_PPG0_AND43_out = (A[7] & B[2]);



assign Multiplier0_PPG0_AND44_out = (A[6] & B[3]);



assign Multiplier0_PPG0_AND45_out = (A[5] & B[4]);



assign Multiplier0_PPG0_AND46_out = (A[4] & B[5]);



assign Multiplier0_PPG0_AND47_out = (A[3] & B[6]);



assign Multiplier0_PPG0_AND48_out = (A[2] & B[7]);



assign Multiplier0_PPG0_AND49_out = (A[7] & B[3]);



assign Multiplier0_PPG0_AND50_out = (A[6] & B[4]);



assign Multiplier0_PPG0_AND51_out = (A[5] & B[5]);



assign Multiplier0_PPG0_AND52_out = (A[4] & B[6]);



assign Multiplier0_PPG0_AND53_out = (A[3] & B[7]);



assign Multiplier0_PPG0_AND54_out = (A[7] & B[4]);



assign Multiplier0_PPG0_AND55_out = (A[6] & B[5]);



assign Multiplier0_PPG0_AND56_out = (A[5] & B[6]);



assign Multiplier0_PPG0_AND57_out = (A[4] & B[7]);



assign Multiplier0_PPG0_AND58_out = (A[7] & B[5]);



assign Multiplier0_PPG0_AND59_out = (A[6] & B[6]);



assign Multiplier0_PPG0_AND60_out = (A[5] & B[7]);



assign Multiplier0_PPG0_AND61_out = (A[7] & B[6]);



assign Multiplier0_PPG0_AND62_out = (A[6] & B[7]);



assign Multiplier0_PPG0_AND63_out = (A[7] & B[7]);



assign Multiplier0_OutBits_ppg = Multiplier0_PPG0_outs_vec;



assign Multiplier0_CompressorTree0_AC320_out2 = ((Multiplier0_OutBits_ppg[3] & Multiplier0_OutBits_ppg[4]) | Multiplier0_OutBits_ppg[5]);
assign Multiplier0_CompressorTree0_AC320_out1 = (Multiplier0_OutBits_ppg[3] | Multiplier0_OutBits_ppg[4]);



assign Multiplier0_CompressorTree0_AC420_out2 = (((Multiplier0_OutBits_ppg[11] & Multiplier0_OutBits_ppg[12]) | Multiplier0_OutBits_ppg[13]) | Multiplier0_OutBits_ppg[14]);
assign Multiplier0_CompressorTree0_AC420_out1 = (((Multiplier0_OutBits_ppg[13] & Multiplier0_OutBits_ppg[14]) | Multiplier0_OutBits_ppg[11]) | Multiplier0_OutBits_ppg[12]);



assign Multiplier0_CompressorTree0_AC421_out2 = (((Multiplier0_OutBits_ppg[17] & Multiplier0_OutBits_ppg[18]) | Multiplier0_OutBits_ppg[19]) | Multiplier0_OutBits_ppg[20]);
assign Multiplier0_CompressorTree0_AC421_out1 = (((Multiplier0_OutBits_ppg[19] & Multiplier0_OutBits_ppg[20]) | Multiplier0_OutBits_ppg[17]) | Multiplier0_OutBits_ppg[18]);



assign Multiplier0_CompressorTree0_AC422_out2 = (((Multiplier0_OutBits_ppg[24] & Multiplier0_OutBits_ppg[25]) | Multiplier0_OutBits_ppg[26]) | Multiplier0_OutBits_ppg[27]);
assign Multiplier0_CompressorTree0_AC422_out1 = (((Multiplier0_OutBits_ppg[26] & Multiplier0_OutBits_ppg[27]) | Multiplier0_OutBits_ppg[24]) | Multiplier0_OutBits_ppg[25]);



assign Multiplier0_CompressorTree0_AC321_out2 = ((Multiplier0_OutBits_ppg[30] & Multiplier0_OutBits_ppg[31]) | Multiplier0_OutBits_ppg[32]);
assign Multiplier0_CompressorTree0_AC321_out1 = (Multiplier0_OutBits_ppg[30] | Multiplier0_OutBits_ppg[31]);



assign Multiplier0_CompressorTree0_AC322_out2 = ((Multiplier0_OutBits_ppg[33] & Multiplier0_OutBits_ppg[34]) | Multiplier0_OutBits_ppg[35]);
assign Multiplier0_CompressorTree0_AC322_out1 = (Multiplier0_OutBits_ppg[33] | Multiplier0_OutBits_ppg[34]);



assign Multiplier0_CompressorTree0_AC423_out2 = (((Multiplier0_OutBits_ppg[36] & Multiplier0_OutBits_ppg[37]) | Multiplier0_OutBits_ppg[38]) | Multiplier0_OutBits_ppg[39]);
assign Multiplier0_CompressorTree0_AC423_out1 = (((Multiplier0_OutBits_ppg[38] & Multiplier0_OutBits_ppg[39]) | Multiplier0_OutBits_ppg[36]) | Multiplier0_OutBits_ppg[37]);



assign Multiplier0_CompressorTree0_AC323_out2 = ((Multiplier0_OutBits_ppg[40] & Multiplier0_OutBits_ppg[41]) | Multiplier0_OutBits_ppg[42]);
assign Multiplier0_CompressorTree0_AC323_out1 = (Multiplier0_OutBits_ppg[40] | Multiplier0_OutBits_ppg[41]);



assign Multiplier0_CompressorTree0_AC324_out2 = ((Multiplier0_OutBits_ppg[43] & Multiplier0_OutBits_ppg[44]) | Multiplier0_OutBits_ppg[45]);
assign Multiplier0_CompressorTree0_AC324_out1 = (Multiplier0_OutBits_ppg[43] | Multiplier0_OutBits_ppg[44]);



assign Multiplier0_CompressorTree0_AC325_out2 = ((Multiplier0_OutBits_ppg[46] & Multiplier0_OutBits_ppg[47]) | Multiplier0_OutBits_ppg[48]);
assign Multiplier0_CompressorTree0_AC325_out1 = (Multiplier0_OutBits_ppg[46] | Multiplier0_OutBits_ppg[47]);



assign Multiplier0_CompressorTree0_FA0_sum = ((Multiplier0_OutBits_ppg[51] ^ Multiplier0_OutBits_ppg[52]) ^ Multiplier0_OutBits_ppg[53]);
assign Multiplier0_CompressorTree0_FA0_cout = (((Multiplier0_OutBits_ppg[51] & Multiplier0_OutBits_ppg[52]) | (Multiplier0_OutBits_ppg[51] & Multiplier0_OutBits_ppg[53])) | (Multiplier0_OutBits_ppg[52] & Multiplier0_OutBits_ppg[53]));



assign Multiplier0_CompressorTree0_AC424_out2 = (((Multiplier0_OutBits_ppg[23] & Multiplier0_OutBits_ppg[21]) | Multiplier0_CompressorTree0_AC422_out1) | Multiplier0_CompressorTree0_AC422_out2);
assign Multiplier0_CompressorTree0_AC424_out1 = (((Multiplier0_CompressorTree0_AC422_out1 & Multiplier0_CompressorTree0_AC422_out2) | Multiplier0_OutBits_ppg[23]) | Multiplier0_OutBits_ppg[21]);



assign Multiplier0_CompressorTree0_AC326_out2 = ((Multiplier0_CompressorTree0_AC322_out2 & Multiplier0_OutBits_ppg[28]) | Multiplier0_OutBits_ppg[29]);
assign Multiplier0_CompressorTree0_AC326_out1 = (Multiplier0_CompressorTree0_AC322_out2 | Multiplier0_OutBits_ppg[28]);



assign Multiplier0_CompressorTree0_AC327_out2 = ((Multiplier0_CompressorTree0_AC322_out1 & Multiplier0_CompressorTree0_AC321_out2) | Multiplier0_CompressorTree0_AC321_out1);
assign Multiplier0_CompressorTree0_AC327_out1 = (Multiplier0_CompressorTree0_AC322_out1 | Multiplier0_CompressorTree0_AC321_out2);



assign Multiplier0_CompressorTree0_AC328_out2 = ((Multiplier0_CompressorTree0_AC423_out2 & Multiplier0_CompressorTree0_AC323_out1) | Multiplier0_CompressorTree0_AC323_out2);
assign Multiplier0_CompressorTree0_AC328_out1 = (Multiplier0_CompressorTree0_AC423_out2 | Multiplier0_CompressorTree0_AC323_out1);



assign Multiplier0_CompressorTree0_FA1_sum = ((Multiplier0_CompressorTree0_FA0_sum ^ Multiplier0_OutBits_ppg[49]) ^ Multiplier0_OutBits_ppg[50]);
assign Multiplier0_CompressorTree0_FA1_cout = (((Multiplier0_CompressorTree0_FA0_sum & Multiplier0_OutBits_ppg[49]) | (Multiplier0_CompressorTree0_FA0_sum & Multiplier0_OutBits_ppg[50])) | (Multiplier0_OutBits_ppg[49] & Multiplier0_OutBits_ppg[50]));



assign Multiplier0_CompressorTree0_FA2_sum = ((Multiplier0_CompressorTree0_FA0_cout ^ Multiplier0_OutBits_ppg[57]) ^ Multiplier0_OutBits_ppg[55]);
assign Multiplier0_CompressorTree0_FA2_cout = (((Multiplier0_CompressorTree0_FA0_cout & Multiplier0_OutBits_ppg[57]) | (Multiplier0_CompressorTree0_FA0_cout & Multiplier0_OutBits_ppg[55])) | (Multiplier0_OutBits_ppg[57] & Multiplier0_OutBits_ppg[55]));



assign Multiplier0_CompressorTree0_HA0_sum = (Multiplier0_OutBits_ppg[59] ^ Multiplier0_OutBits_ppg[58]);
assign Multiplier0_CompressorTree0_HA0_cout = (Multiplier0_OutBits_ppg[59] & Multiplier0_OutBits_ppg[58]);



assign Multiplier0_CompressorTree0_AC425_out2 = (((Multiplier0_OutBits_ppg[8] & Multiplier0_OutBits_ppg[7]) | Multiplier0_OutBits_ppg[6]) | Multiplier0_OutBits_ppg[9]);
assign Multiplier0_CompressorTree0_AC425_out1 = (((Multiplier0_OutBits_ppg[6] & Multiplier0_OutBits_ppg[9]) | Multiplier0_OutBits_ppg[8]) | Multiplier0_OutBits_ppg[7]);



assign Multiplier0_CompressorTree0_AC329_out2 = ((Multiplier0_OutBits_ppg[10] & Multiplier0_CompressorTree0_AC420_out2) | Multiplier0_CompressorTree0_AC420_out1);
assign Multiplier0_CompressorTree0_AC329_out1 = (Multiplier0_OutBits_ppg[10] | Multiplier0_CompressorTree0_AC420_out2);



assign Multiplier0_CompressorTree0_AC426_out2 = (((Multiplier0_OutBits_ppg[15] & Multiplier0_OutBits_ppg[16]) | Multiplier0_CompressorTree0_AC421_out1) | Multiplier0_CompressorTree0_AC421_out2);
assign Multiplier0_CompressorTree0_AC426_out1 = (((Multiplier0_CompressorTree0_AC421_out1 & Multiplier0_CompressorTree0_AC421_out2) | Multiplier0_OutBits_ppg[15]) | Multiplier0_OutBits_ppg[16]);



assign Multiplier0_CompressorTree0_AC3210_out2 = ((Multiplier0_OutBits_ppg[22] & Multiplier0_CompressorTree0_AC424_out2) | Multiplier0_CompressorTree0_AC424_out1);
assign Multiplier0_CompressorTree0_AC3210_out1 = (Multiplier0_OutBits_ppg[22] | Multiplier0_CompressorTree0_AC424_out2);



assign Multiplier0_CompressorTree0_AC427_out2 = (((Multiplier0_CompressorTree0_AC326_out1 & Multiplier0_CompressorTree0_AC327_out2) | Multiplier0_CompressorTree0_AC327_out1) | Multiplier0_CompressorTree0_AC326_out2);
assign Multiplier0_CompressorTree0_AC427_out1 = (((Multiplier0_CompressorTree0_AC327_out1 & Multiplier0_CompressorTree0_AC326_out2) | Multiplier0_CompressorTree0_AC326_out1) | Multiplier0_CompressorTree0_AC327_out2);



assign Multiplier0_CompressorTree0_AC3211_out2 = ((Multiplier0_CompressorTree0_AC328_out1 & Multiplier0_CompressorTree0_AC328_out2) | Multiplier0_CompressorTree0_AC423_out1);
assign Multiplier0_CompressorTree0_AC3211_out1 = (Multiplier0_CompressorTree0_AC328_out1 | Multiplier0_CompressorTree0_AC328_out2);



assign Multiplier0_CompressorTree0_FA3_sum = ((Multiplier0_CompressorTree0_AC325_out1 ^ Multiplier0_CompressorTree0_AC324_out2) ^ Multiplier0_CompressorTree0_AC324_out1);
assign Multiplier0_CompressorTree0_FA3_cout = (((Multiplier0_CompressorTree0_AC325_out1 & Multiplier0_CompressorTree0_AC324_out2) | (Multiplier0_CompressorTree0_AC325_out1 & Multiplier0_CompressorTree0_AC324_out1)) | (Multiplier0_CompressorTree0_AC324_out2 & Multiplier0_CompressorTree0_AC324_out1));



assign Multiplier0_CompressorTree0_FA4_sum = ((Multiplier0_CompressorTree0_FA2_sum ^ Multiplier0_OutBits_ppg[54]) ^ Multiplier0_OutBits_ppg[56]);
assign Multiplier0_CompressorTree0_FA4_cout = (((Multiplier0_CompressorTree0_FA2_sum & Multiplier0_OutBits_ppg[54]) | (Multiplier0_CompressorTree0_FA2_sum & Multiplier0_OutBits_ppg[56])) | (Multiplier0_OutBits_ppg[54] & Multiplier0_OutBits_ppg[56]));



assign Multiplier0_CompressorTree0_FA5_sum = ((Multiplier0_CompressorTree0_HA0_sum ^ Multiplier0_CompressorTree0_FA2_cout) ^ Multiplier0_OutBits_ppg[60]);
assign Multiplier0_CompressorTree0_FA5_cout = (((Multiplier0_CompressorTree0_HA0_sum & Multiplier0_CompressorTree0_FA2_cout) | (Multiplier0_CompressorTree0_HA0_sum & Multiplier0_OutBits_ppg[60])) | (Multiplier0_CompressorTree0_FA2_cout & Multiplier0_OutBits_ppg[60]));



assign Multiplier0_CompressorTree0_FA6_sum = ((Multiplier0_CompressorTree0_HA0_cout ^ Multiplier0_OutBits_ppg[61]) ^ Multiplier0_OutBits_ppg[62]);
assign Multiplier0_CompressorTree0_FA6_cout = (((Multiplier0_CompressorTree0_HA0_cout & Multiplier0_OutBits_ppg[61]) | (Multiplier0_CompressorTree0_HA0_cout & Multiplier0_OutBits_ppg[62])) | (Multiplier0_OutBits_ppg[61] & Multiplier0_OutBits_ppg[62]));



assign OutBits_ct = Multiplier0_CompressorTree0_outs_vec;



assign KoggeStone0_PG_Generator00_p = OutBits_ct[0];
assign KoggeStone0_PG_Generator00_g = 1'h0;



assign KoggeStone0_PG_Generator10_p = (OutBits_ct[1] ^ OutBits_ct[2]);
assign KoggeStone0_PG_Generator10_g = (OutBits_ct[1] & OutBits_ct[2]);



assign KoggeStone0_PG_Generator11_p = (OutBits_ct[3] ^ OutBits_ct[4]);
assign KoggeStone0_PG_Generator11_g = (OutBits_ct[3] & OutBits_ct[4]);



assign KoggeStone0_PG_Generator12_p = (OutBits_ct[5] ^ OutBits_ct[6]);
assign KoggeStone0_PG_Generator12_g = (OutBits_ct[5] & OutBits_ct[6]);



assign KoggeStone0_PG_Generator13_p = (OutBits_ct[7] ^ OutBits_ct[8]);
assign KoggeStone0_PG_Generator13_g = (OutBits_ct[7] & OutBits_ct[8]);



assign KoggeStone0_PG_Generator14_p = (OutBits_ct[9] ^ OutBits_ct[10]);
assign KoggeStone0_PG_Generator14_g = (OutBits_ct[9] & OutBits_ct[10]);



assign KoggeStone0_PG_Generator15_p = (OutBits_ct[11] ^ OutBits_ct[12]);
assign KoggeStone0_PG_Generator15_g = (OutBits_ct[11] & OutBits_ct[12]);



assign KoggeStone0_PG_Generator16_p = (OutBits_ct[13] ^ OutBits_ct[14]);
assign KoggeStone0_PG_Generator16_g = (OutBits_ct[13] & OutBits_ct[14]);



assign KoggeStone0_PG_Generator17_p = (OutBits_ct[15] ^ OutBits_ct[16]);
assign KoggeStone0_PG_Generator17_g = (OutBits_ct[15] & OutBits_ct[16]);



assign KoggeStone0_PG_Generator18_p = (OutBits_ct[17] ^ OutBits_ct[18]);
assign KoggeStone0_PG_Generator18_g = (OutBits_ct[17] & OutBits_ct[18]);



assign KoggeStone0_PG_Generator19_p = (OutBits_ct[19] ^ OutBits_ct[20]);
assign KoggeStone0_PG_Generator19_g = (OutBits_ct[19] & OutBits_ct[20]);



assign KoggeStone0_PG_Generator110_p = (OutBits_ct[21] ^ OutBits_ct[22]);
assign KoggeStone0_PG_Generator110_g = (OutBits_ct[21] & OutBits_ct[22]);



assign KoggeStone0_PG_Generator111_p = (OutBits_ct[23] ^ OutBits_ct[24]);
assign KoggeStone0_PG_Generator111_g = (OutBits_ct[23] & OutBits_ct[24]);



assign KoggeStone0_PG_Generator112_p = (OutBits_ct[25] ^ OutBits_ct[26]);
assign KoggeStone0_PG_Generator112_g = (OutBits_ct[25] & OutBits_ct[26]);



assign KoggeStone0_PG_Generator113_p = (OutBits_ct[27] ^ OutBits_ct[28]);
assign KoggeStone0_PG_Generator113_g = (OutBits_ct[27] & OutBits_ct[28]);



assign KoggeStone0_GrayCircle0_go = (KoggeStone0_PG_Generator10_g | (KoggeStone0_PG_Generator10_p & KoggeStone0_PG_Generator00_g));



assign KoggeStone0_BlackCircle0_po = (KoggeStone0_PG_Generator11_p & KoggeStone0_PG_Generator10_p);
assign KoggeStone0_BlackCircle0_go = (KoggeStone0_PG_Generator11_g | (KoggeStone0_PG_Generator11_p & KoggeStone0_PG_Generator10_g));



assign KoggeStone0_BlackCircle1_po = (KoggeStone0_PG_Generator12_p & KoggeStone0_PG_Generator11_p);
assign KoggeStone0_BlackCircle1_go = (KoggeStone0_PG_Generator12_g | (KoggeStone0_PG_Generator12_p & KoggeStone0_PG_Generator11_g));



assign KoggeStone0_BlackCircle2_po = (KoggeStone0_PG_Generator13_p & KoggeStone0_PG_Generator12_p);
assign KoggeStone0_BlackCircle2_go = (KoggeStone0_PG_Generator13_g | (KoggeStone0_PG_Generator13_p & KoggeStone0_PG_Generator12_g));



assign KoggeStone0_BlackCircle3_po = (KoggeStone0_PG_Generator14_p & KoggeStone0_PG_Generator13_p);
assign KoggeStone0_BlackCircle3_go = (KoggeStone0_PG_Generator14_g | (KoggeStone0_PG_Generator14_p & KoggeStone0_PG_Generator13_g));



assign KoggeStone0_BlackCircle4_po = (KoggeStone0_PG_Generator15_p & KoggeStone0_PG_Generator14_p);
assign KoggeStone0_BlackCircle4_go = (KoggeStone0_PG_Generator15_g | (KoggeStone0_PG_Generator15_p & KoggeStone0_PG_Generator14_g));



assign KoggeStone0_BlackCircle5_po = (KoggeStone0_PG_Generator16_p & KoggeStone0_PG_Generator15_p);
assign KoggeStone0_BlackCircle5_go = (KoggeStone0_PG_Generator16_g | (KoggeStone0_PG_Generator16_p & KoggeStone0_PG_Generator15_g));



assign KoggeStone0_BlackCircle6_po = (KoggeStone0_PG_Generator17_p & KoggeStone0_PG_Generator16_p);
assign KoggeStone0_BlackCircle6_go = (KoggeStone0_PG_Generator17_g | (KoggeStone0_PG_Generator17_p & KoggeStone0_PG_Generator16_g));



assign KoggeStone0_BlackCircle7_po = (KoggeStone0_PG_Generator18_p & KoggeStone0_PG_Generator17_p);
assign KoggeStone0_BlackCircle7_go = (KoggeStone0_PG_Generator18_g | (KoggeStone0_PG_Generator18_p & KoggeStone0_PG_Generator17_g));



assign KoggeStone0_BlackCircle8_po = (KoggeStone0_PG_Generator19_p & KoggeStone0_PG_Generator18_p);
assign KoggeStone0_BlackCircle8_go = (KoggeStone0_PG_Generator19_g | (KoggeStone0_PG_Generator19_p & KoggeStone0_PG_Generator18_g));



assign KoggeStone0_BlackCircle9_po = (KoggeStone0_PG_Generator110_p & KoggeStone0_PG_Generator19_p);
assign KoggeStone0_BlackCircle9_go = (KoggeStone0_PG_Generator110_g | (KoggeStone0_PG_Generator110_p & KoggeStone0_PG_Generator19_g));



assign KoggeStone0_BlackCircle10_po = (KoggeStone0_PG_Generator111_p & KoggeStone0_PG_Generator110_p);
assign KoggeStone0_BlackCircle10_go = (KoggeStone0_PG_Generator111_g | (KoggeStone0_PG_Generator111_p & KoggeStone0_PG_Generator110_g));



assign KoggeStone0_BlackCircle11_po = (KoggeStone0_PG_Generator112_p & KoggeStone0_PG_Generator111_p);
assign KoggeStone0_BlackCircle11_go = (KoggeStone0_PG_Generator112_g | (KoggeStone0_PG_Generator112_p & KoggeStone0_PG_Generator111_g));



assign KoggeStone0_BlackCircle12_po = (KoggeStone0_PG_Generator113_p & KoggeStone0_PG_Generator112_p);
assign KoggeStone0_BlackCircle12_go = (KoggeStone0_PG_Generator113_g | (KoggeStone0_PG_Generator113_p & KoggeStone0_PG_Generator112_g));



assign KoggeStone0_GrayCircle1_go = (KoggeStone0_BlackCircle0_go | (KoggeStone0_BlackCircle0_po & KoggeStone0_PG_Generator00_g));



assign KoggeStone0_GrayCircle2_go = (KoggeStone0_BlackCircle1_go | (KoggeStone0_BlackCircle1_po & KoggeStone0_GrayCircle0_go));



assign KoggeStone0_BlackCircle13_po = (KoggeStone0_BlackCircle2_po & KoggeStone0_BlackCircle0_po);
assign KoggeStone0_BlackCircle13_go = (KoggeStone0_BlackCircle2_go | (KoggeStone0_BlackCircle2_po & KoggeStone0_BlackCircle0_go));



assign KoggeStone0_BlackCircle14_po = (KoggeStone0_BlackCircle3_po & KoggeStone0_BlackCircle1_po);
assign KoggeStone0_BlackCircle14_go = (KoggeStone0_BlackCircle3_go | (KoggeStone0_BlackCircle3_po & KoggeStone0_BlackCircle1_go));



assign KoggeStone0_BlackCircle15_po = (KoggeStone0_BlackCircle4_po & KoggeStone0_BlackCircle2_po);
assign KoggeStone0_BlackCircle15_go = (KoggeStone0_BlackCircle4_go | (KoggeStone0_BlackCircle4_po & KoggeStone0_BlackCircle2_go));



assign KoggeStone0_BlackCircle16_po = (KoggeStone0_BlackCircle5_po & KoggeStone0_BlackCircle3_po);
assign KoggeStone0_BlackCircle16_go = (KoggeStone0_BlackCircle5_go | (KoggeStone0_BlackCircle5_po & KoggeStone0_BlackCircle3_go));



assign KoggeStone0_BlackCircle17_po = (KoggeStone0_BlackCircle6_po & KoggeStone0_BlackCircle4_po);
assign KoggeStone0_BlackCircle17_go = (KoggeStone0_BlackCircle6_go | (KoggeStone0_BlackCircle6_po & KoggeStone0_BlackCircle4_go));



assign KoggeStone0_BlackCircle18_po = (KoggeStone0_BlackCircle7_po & KoggeStone0_BlackCircle5_po);
assign KoggeStone0_BlackCircle18_go = (KoggeStone0_BlackCircle7_go | (KoggeStone0_BlackCircle7_po & KoggeStone0_BlackCircle5_go));



assign KoggeStone0_BlackCircle19_po = (KoggeStone0_BlackCircle8_po & KoggeStone0_BlackCircle6_po);
assign KoggeStone0_BlackCircle19_go = (KoggeStone0_BlackCircle8_go | (KoggeStone0_BlackCircle8_po & KoggeStone0_BlackCircle6_go));



assign KoggeStone0_BlackCircle20_po = (KoggeStone0_BlackCircle9_po & KoggeStone0_BlackCircle7_po);
assign KoggeStone0_BlackCircle20_go = (KoggeStone0_BlackCircle9_go | (KoggeStone0_BlackCircle9_po & KoggeStone0_BlackCircle7_go));



assign KoggeStone0_BlackCircle21_po = (KoggeStone0_BlackCircle10_po & KoggeStone0_BlackCircle8_po);
assign KoggeStone0_BlackCircle21_go = (KoggeStone0_BlackCircle10_go | (KoggeStone0_BlackCircle10_po & KoggeStone0_BlackCircle8_go));



assign KoggeStone0_BlackCircle22_po = (KoggeStone0_BlackCircle11_po & KoggeStone0_BlackCircle9_po);
assign KoggeStone0_BlackCircle22_go = (KoggeStone0_BlackCircle11_go | (KoggeStone0_BlackCircle11_po & KoggeStone0_BlackCircle9_go));



assign KoggeStone0_BlackCircle23_po = (KoggeStone0_BlackCircle12_po & KoggeStone0_BlackCircle10_po);
assign KoggeStone0_BlackCircle23_go = (KoggeStone0_BlackCircle12_go | (KoggeStone0_BlackCircle12_po & KoggeStone0_BlackCircle10_go));



assign KoggeStone0_GrayCircle3_go = (KoggeStone0_BlackCircle13_go | (KoggeStone0_BlackCircle13_po & KoggeStone0_PG_Generator00_g));



assign KoggeStone0_GrayCircle4_go = (KoggeStone0_BlackCircle14_go | (KoggeStone0_BlackCircle14_po & KoggeStone0_GrayCircle0_go));



assign KoggeStone0_GrayCircle5_go = (KoggeStone0_BlackCircle15_go | (KoggeStone0_BlackCircle15_po & KoggeStone0_GrayCircle1_go));



assign KoggeStone0_GrayCircle6_go = (KoggeStone0_BlackCircle16_go | (KoggeStone0_BlackCircle16_po & KoggeStone0_GrayCircle2_go));



assign KoggeStone0_BlackCircle24_po = (KoggeStone0_BlackCircle17_po & KoggeStone0_BlackCircle13_po);
assign KoggeStone0_BlackCircle24_go = (KoggeStone0_BlackCircle17_go | (KoggeStone0_BlackCircle17_po & KoggeStone0_BlackCircle13_go));



assign KoggeStone0_BlackCircle25_po = (KoggeStone0_BlackCircle18_po & KoggeStone0_BlackCircle14_po);
assign KoggeStone0_BlackCircle25_go = (KoggeStone0_BlackCircle18_go | (KoggeStone0_BlackCircle18_po & KoggeStone0_BlackCircle14_go));



assign KoggeStone0_BlackCircle26_po = (KoggeStone0_BlackCircle19_po & KoggeStone0_BlackCircle15_po);
assign KoggeStone0_BlackCircle26_go = (KoggeStone0_BlackCircle19_go | (KoggeStone0_BlackCircle19_po & KoggeStone0_BlackCircle15_go));



assign KoggeStone0_BlackCircle27_po = (KoggeStone0_BlackCircle20_po & KoggeStone0_BlackCircle16_po);
assign KoggeStone0_BlackCircle27_go = (KoggeStone0_BlackCircle20_go | (KoggeStone0_BlackCircle20_po & KoggeStone0_BlackCircle16_go));



assign KoggeStone0_BlackCircle28_po = (KoggeStone0_BlackCircle21_po & KoggeStone0_BlackCircle17_po);
assign KoggeStone0_BlackCircle28_go = (KoggeStone0_BlackCircle21_go | (KoggeStone0_BlackCircle21_po & KoggeStone0_BlackCircle17_go));



assign KoggeStone0_BlackCircle29_po = (KoggeStone0_BlackCircle22_po & KoggeStone0_BlackCircle18_po);
assign KoggeStone0_BlackCircle29_go = (KoggeStone0_BlackCircle22_go | (KoggeStone0_BlackCircle22_po & KoggeStone0_BlackCircle18_go));



assign KoggeStone0_BlackCircle30_po = (KoggeStone0_BlackCircle23_po & KoggeStone0_BlackCircle19_po);
assign KoggeStone0_BlackCircle30_go = (KoggeStone0_BlackCircle23_go | (KoggeStone0_BlackCircle23_po & KoggeStone0_BlackCircle19_go));



assign KoggeStone0_GrayCircle7_go = (KoggeStone0_BlackCircle24_go | (KoggeStone0_BlackCircle24_po & KoggeStone0_PG_Generator00_g));



assign KoggeStone0_GrayCircle8_go = (KoggeStone0_BlackCircle25_go | (KoggeStone0_BlackCircle25_po & KoggeStone0_GrayCircle0_go));



assign KoggeStone0_GrayCircle9_go = (KoggeStone0_BlackCircle26_go | (KoggeStone0_BlackCircle26_po & KoggeStone0_GrayCircle1_go));



assign KoggeStone0_GrayCircle10_go = (KoggeStone0_BlackCircle27_go | (KoggeStone0_BlackCircle27_po & KoggeStone0_GrayCircle2_go));



assign KoggeStone0_GrayCircle11_go = (KoggeStone0_BlackCircle28_go | (KoggeStone0_BlackCircle28_po & KoggeStone0_GrayCircle3_go));



assign KoggeStone0_GrayCircle12_go = (KoggeStone0_BlackCircle29_go | (KoggeStone0_BlackCircle29_po & KoggeStone0_GrayCircle4_go));



assign KoggeStone0_GrayCircle13_go = (KoggeStone0_BlackCircle30_go | (KoggeStone0_BlackCircle30_po & KoggeStone0_GrayCircle5_go));



assign KoggeStone0_FinalSum0_sum = (KoggeStone0_PG_Generator10_p ^ KoggeStone0_PG_Generator00_g);



assign KoggeStone0_FinalSum1_sum = (KoggeStone0_PG_Generator11_p ^ KoggeStone0_GrayCircle0_go);



assign KoggeStone0_FinalSum2_sum = (KoggeStone0_PG_Generator12_p ^ KoggeStone0_GrayCircle1_go);



assign KoggeStone0_FinalSum3_sum = (KoggeStone0_PG_Generator13_p ^ KoggeStone0_GrayCircle2_go);



assign KoggeStone0_FinalSum4_sum = (KoggeStone0_PG_Generator14_p ^ KoggeStone0_GrayCircle3_go);



assign KoggeStone0_FinalSum5_sum = (KoggeStone0_PG_Generator15_p ^ KoggeStone0_GrayCircle4_go);



assign KoggeStone0_FinalSum6_sum = (KoggeStone0_PG_Generator16_p ^ KoggeStone0_GrayCircle5_go);



assign KoggeStone0_FinalSum7_sum = (KoggeStone0_PG_Generator17_p ^ KoggeStone0_GrayCircle6_go);



assign KoggeStone0_FinalSum8_sum = (KoggeStone0_PG_Generator18_p ^ KoggeStone0_GrayCircle7_go);



assign KoggeStone0_FinalSum9_sum = (KoggeStone0_PG_Generator19_p ^ KoggeStone0_GrayCircle8_go);



assign KoggeStone0_FinalSum10_sum = (KoggeStone0_PG_Generator110_p ^ KoggeStone0_GrayCircle9_go);



assign KoggeStone0_FinalSum11_sum = (KoggeStone0_PG_Generator111_p ^ KoggeStone0_GrayCircle10_go);



assign KoggeStone0_FinalSum12_sum = (KoggeStone0_PG_Generator112_p ^ KoggeStone0_GrayCircle11_go);



assign KoggeStone0_FinalSum13_sum = (KoggeStone0_PG_Generator113_p ^ KoggeStone0_GrayCircle12_go);



assign OUTS = KoggeStone0_outs_vec;

endmodule
